services:
  db:
    image: mysql:8.4
    container_name: ehcidb_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: ehcidb
      MYSQL_USER: ehci
      MYSQL_PASSWORD: ehci_pw
    ports:
      - "3307:3306"
    command: --local-infile=1 --secure-file-priv=""
    volumes:
      - mysqldata:/var/lib/mysql
      - ./data:/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  mysqldata:
